language: python
addons:
  apt:
    packages:
    - openmpi-bin
    - libopenmpi-dev

python:
    - "2.7"
    - "3.5"
    - "3.6"
install:
    - pip install --upgrade pip setuptools wheel
    - pip install mpi4py # for mpi
    - pip install pytest runtests # for testing
    - pip install -r requirements.txt 
script:
    - python run-mpitests.py --single
