language: python
python:
    - "2.7"
    - "3.5"
    - "3.6"
install:
    - pip install --upgrade pip setuptools wheel pytest runtests
    - pip install -r requirements.txt
script:
    - python run-mpitests.py --single
